version: '3'

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
   
  app:
    build: .
    command: bash -c "npm install && npm run migration && npm start"  
    depends_on:
      - db

    